# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
   include:
     - dev
     - master
     - feature/*
  paths:
    exclude:
      - .gitignore
      - README.md

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'     
  buildPlatform: 'Any CPU'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: 
    buildConfiguration: 'Release'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'dev') }}: 
    buildConfiguration: 'Beta'
  ${{ else }}:
    buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  condition: and(succeeded(), eq(variables.skipTests, 'false'))
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: NuGetCommand@2
  condition: and(succeeded(), in(variables.buildConfiguration, 'Release', 'Beta'))
  inputs:
    command: push
    packagesToPush: '$(Agent.BuildDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'