# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
   include:
     - dev
     - master
     - feature/*
  paths:
    exclude:
      - .gitignore
      - README.md

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'     
  buildPlatform: 'Any CPU'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: 
    buildConfiguration: 'Release'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'dev') }}: 
    buildConfiguration: 'Dev'
  ${{ else }}:
    buildConfiguration: 'Debug'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Retrieving stable build identifier"
      [int] $hours=$(Get-Date -format hh)
      [int] $minutes=$(Get-Date -format mm)
      [int] $seconds=$(Get-Date -format ss)
      [int] $buildSecond=([int]$hours) * 3600 + ([int]$minutes) * 60 + ([int]$seconds)
      Write-Host "##vso[task.setvariable variable=buildSecond]$buildSecond"

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '-p:Build=$(buildSecond)'

- task: DotNetCoreCLI@2
  condition: and(succeeded(), eq(variables.skipTests, 'false'))
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: NuGetCommand@2
  condition: and(succeeded(), in(variables.buildConfiguration, 'Release', 'Dev', 'Beta'), eq(variables.skipPush, 'false'))
  inputs:
    command: push
    packagesToPush: '$(Agent.BuildDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'