syntax = "proto3";
package Bitub.Dto.Concept;

import "Common.proto";
import "google/protobuf/timestamp.proto";

// Version 1.3

option csharp_namespace = "Bitub.Dto.Concept";
option java_package = "bitub.dto";

// A domain space
message ELDomain {
	Qualifier canonical = 1;
	repeated ELConcept concepts = 2;
}

// A general composite concept
message ELConcept {
	Qualifier canonical = 1; // canonical name
	
	repeated ELFeature feature = 2;

	repeated Qualifier subsumes = 3; // hyponyms (conjunction if > 1)
	repeated Qualifier equivalent = 4; // equivalents (conjunction if > 1)
}

// A feature is either a role or a data concept
message ELFeature {
	Qualifier name = 1;
	oneof feature {
		RoleConcept role = 2;
		DataConcept data = 3;
	}
}

// A role concept
message RoleConcept {
	Qualifier qualifier = 1;
}

// A feature data concept
message DataConcept {
	DataType type = 1;
	DataUnitSI unit = 2;
	DataUnitPrefix unitPrefix = 3;
	DataOp op = 4;
	oneof dataValue {
		double digit = 5;
		string value = 6;
		google.protobuf.Timestamp timeStamp = 7;
		Logical logical = 8;
		GlobalUniqueId guid = 9;
	}
}
